# Generated by Django 5.0.1 on 2024-02-06 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parawords_app', '0003_paragraph_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parawords_app.registeruser'),
        ),
    ]
