# Generated by Django 5.0.1 on 2024-02-06 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parawords_app', '0005_alter_word_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paragraph',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='paragraph_id',
            new_name='paragraph',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='user_id',
            new_name='user',
        ),
    ]
