version: '3'
services:
  web:
    build: .
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres@1234
      POSTGRES_DB: ParaWords
    
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest    
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres@1234
        POSTGRES_DB: ParaWords
    volumes:
        - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:      